spring:
  application:
    name: business-backend
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=mymonty_business;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong@Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080
